### ISSUE TITLE
Not working with Asterisk 14

### ISSUE THREAD

**Issue by marcoacarvalho** [dagmoller/monast#3]
Probably due to changes in AMI on Asterisk v14, Monast is not working on this version:

[Thu Mar 16 16:18:17 2017] NOTICE   :: Initializing Monast AMI Interface...
[Thu Mar 16 16:18:17 2017] NOTICE   :: Parsing config file /etc/monast.conf
[Thu Mar 16 16:18:17 2017] NOTICE   :: Server Test :: AMI Connected...
[Thu Mar 16 16:18:17 2017] ERROR    :: Server Test :: Error Requesting Asterisk Version, reason: Command output follows

http://lists.digium.com/pipermail/asterisk-commits/2015-April/072904.html

**Comment by dagmoller** [comment]
Monast uses starpy to connect to AMI, but it does not support new AMI output format yet...

**Comment by dagmoller** [comment]
You need to get starpy from github(https://github.com/asterisk/starpy) and apply the patch below...

[asterisk-14.txt](https://github.com/dagmoller/monast/files/868635/asterisk-14.txt)

**Comment by marcoacarvalho** [comment]
Thanx
I will check this out
