### ISSUE TITLE
MonAst with CentOS 7 e PHP 5.4

### ISSUE THREAD

**Issue by emanuelsena** [dagmoller/monast#5]
# pear install HTTP_Client
WARNING: "pear/HTTP_Client" is deprecated in favor of "pear/HTTP_Request2"
WARNING: channel "pear.php.net" has updated its protocols, use "pear channel-update pear.php.net" to update
WARNING: "pear/HTTP_Request" is deprecated in favor of "pear/HTTP_Request2"
WARNING: "pear/Net_URL" is deprecated in favor of "pear/Net_URL2"
pear/Net_Socket requires PEAR Installer (version >= 1.10.1), installed version is 1.9.4
pear/HTTP_Request requires package "pear/Net_Socket" (version >= 1.0.7)
pear/HTTP_Client requires package "pear/HTTP_Request" (version >= 1.4.0)
No valid packages found
install failed

**Comment by dagmoller** [comment]
try to run:
# pear channel-update pear.php.net 

and install deps again.
