### ISSUE TITLE
Debian 9 and php7

### ISSUE THREAD

**Issue by aikhua** [dagmoller/monast#7]
Hi, 
On Debian 9  with php7 cant open start page.
tail -1  /var/log/apache2/error.log
[Mon Oct 02 12:33:20.533800 2017] [:error] [pid 21622] [client х.х.х.х:33562] PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /usr/share/php/HTTP/Client.php on line 179

**Comment by dagmoller** [comment]
This is not related to monast... its related to PEAR HTTP_Client package...
